### ISSUE TITLE
Allowing leading zeros for simple right-aligned number formatter

### ISSUE THREAD

**Issue by nmay231** [volkerdobler/insertnums#13]
Sorry if this is a bit much. :)

I'm going to open a few issues with some ideas, one for each so they can be discussed/closed individually. I've decided this is the best "insert sequence" vscode extension at the moment, mostly because it uses the python mini-formating language and it's actually being updated. I'm probably gonna work on implementing at least some of these as I find time.

First up, allow leading zeros (and maybe spaces) for numbers as a simple left-aligned formatter. For example, the following command pairs would be equivalent:

- ` 1` <==> `1~ >2`
- `001` <==> `1~0>3`

**Comment by volkerdobler** [comment]
> Sorry if this is a bit much. :)
> 
> I'm going to open a few issues with some ideas, one for each so they can be discussed/closed individually. I've decided this is the best "insert sequence" vscode extension at the moment, mostly because it uses the python mini-formating language and it's actually being updated. I'm probably gonna work on implementing at least some of these as I find time.
> 
> First up, allow leading zeros (and maybe spaces) for numbers as a simple left-aligned formatter. For example, the following command pairs would be equivalent:
> 
> * ` 1` <==> `1~ >2`
> * `001` <==> `1~0>3`

I like the idea, but we have to be careful and think about the situation, if the format starts with "0x", which means, the numbers should be hex.
Currently, the input does not allow leading zeros (or to be precise, only when a x follows ;-) ), but I can change this. But 0 could be the only option, e.g. blanks can not be handeled the same way. Because if people, by accident, insert a few blanks at the beginning, the numbers will be formated, and they might not like it? Solution: maybe use "_" instead of " " as leading char?
So for this special situation, "001" as short version of "1~03" whould save 1 digit. What do you think about it?

**Comment by nmay231** [comment]
>  blanks can not be handeled the same way. Because if people, by accident, insert a few blanks at the beginning, the numbers will be formated, and they might not like it?

This would be much less of an issue after #10 is complete.

> So for this special situation, "001" as short version of "1~03" whould save 1 digit. What do you think about it?

It's not about less typing (though it is easier to type because there are fewer *unique* characters); it's more because there's precedence in other extensions (e.g. [this one](https://marketplace.visualstudio.com/items?itemName=kuone.sequence-number)) and because it's such a common pattern to left-pad numbers with zeros or spaces. For example, in podcast episodes, values in markdown tables, etc.

To be clear, I think it should only be supported for decimal numbers, but it's also not a high-priority request since it's just an extra convenience.

**Comment by volkerdobler** [comment]
> > blanks can not be handeled the same way. Because if people, by accident, insert a few blanks at the beginning, the numbers will be formated, and they might not like it?
> 
> This would be much less of an issue after #10 is complete.

I am not sure, when and if #10 will be solved. My skills are limited and the only way, of having a preview in vscode seems for me to use decorations. But they are mainly for highlighting text and not inserting content. I found one twitch video from someone who implemented a very easy decoration with additional content, but I am not sure if I can program this by myself.

> 
> > So for this special situation, "001" as short version of "1~03" whould save 1 digit. What do you think about it?
> 
> It's not about less typing (though it is easier to type because there are fewer _unique_ characters); it's more because there's precedence in other extensions (e.g. [this one](https://marketplace.visualstudio.com/items?itemName=kuone.sequence-number)) and because it's such a common pattern to left-pad numbers with zeros or spaces. For example, in podcast episodes, values in markdown tables, etc.
> 
> To be clear, I think it should only be supported for decimal numbers, but it's also not a high-priority request since it's just an extra convenience.

I have implemented this feature with leading three possible chars: zeros, blanks and dots. It will be available with the next version, maybe in 1 to 2 weeks. I would like to check your other issues first. I like the idea of having a "date" counter.

**Comment by volkerdobler** [comment]
> Sorry if this is a bit much. :)
> 
> I'm going to open a few issues with some ideas, one for each so they can be discussed/closed individually. I've decided this is the best "insert sequence" vscode extension at the moment, mostly because it uses the python mini-formating language and it's actually being updated. I'm probably gonna work on implementing at least some of these as I find time.
> 
> First up, allow leading zeros (and maybe spaces) for numbers as a simple left-aligned formatter. For example, the following command pairs would be equivalent:
> 
> * ` 1` <==> `1~ >2`
> * `001` <==> `1~0>3`

This feature is now included in version 0.9.6 - try it and give me feedback, if you find any bug.

**Comment by volkerdobler** [comment]
Is available now in version 0.10.0 which I just published (and which is working :-) )
