### ISSUE TITLE
Format Date, Time, and Datetime, and allow time increments

### ISSUE THREAD

**Issue by nmay231** [volkerdobler/insertnums#16]
This is quite a bit more complicated than the months feature that is currently present. However, it should be easier using the [`Intl` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts).

I'm thinking of sticking with [python format codes](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) to be consistent with how other things are formatted.

I wish I had this feature a few days ago when I had to rename a bunch of files (payslips). I ended up writing a python script to print out the new file names, and using the vscode 'Bulk Rename' extension, but this would have saved the time of writing the python script.

**Comment by volkerdobler** [comment]
You are right, a full date and time support would be really cool. I will think about it, or if you have any idea or examples, I am happy to insert this in the next version.

**Comment by nmay231** [comment]
I don't have any good ideas about the syntax since it would probably require a form of grouping or escaping characters (something like #14 :slightly_smiling_face: ) to not conflict with current syntax.

An example using the payslips idea: `"2024-01-01":2weeks~"%Y/%m/%d"` => `2024/01/01`, `2024/01/15`, `2024/01/29`, ...

**Comment by volkerdobler** [comment]
I just release version 0.9.6 which includes the first time a date sequence insertion. You can start with % and insert any date (not time so far) in the format year-month-day (-month and -day are optional).
To tell the program what you want to increase, you can use d for days, w for weeks, m for month and y for years (d is the default).

So one example would be "%2024-4-25:w2" which will include different dates, starting from 25 April 2024 and increase two weeks for each iteration.

Let me know, what you think about it.

> This is quite a bit more complicated than the months feature that is currently present. However, it should be easier using the [`Intl` API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts).
> 
> I'm thinking of sticking with [python format codes](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) to be consistent with how other things are formatted.
> 
> I wish I had this feature a few days ago when I had to rename a bunch of files (payslips). I ended up writing a python script to print out the new file names, and using the vscode 'Bulk Rename' extension, but this would have saved the time of writing the python script.

**Comment by volkerdobler** [comment]
Is now available with version 0.10.0. Currently dates only (no time at the moment, but maybe in the future).

**Comment by nmay231** [comment]
Nice! :tada:
