### ISSUE TITLE
Better command palette UX

### ISSUE THREAD

**Issue by nmay231** [volkerdobler/insertnums#17]
There are a couple of small changes to make the overall experience of the command palette a little better.

- [ ] Rename the text description of `insertSeq` to `Insert Number Sequence`. I didn't even know you registered the command to the command palette until I looked through the code because the extension is called `Insert Seq` while the command is `Insert Numbers`. I was searching "seq" and didn't find anything.
- [ ] I would switch the prompt and the placeholder so you always see the text `[<start>][:<step>] ...` and don't have to memorize the formatting special characters.
- [ ] I don't know the history of the commands `insertNums` vs `insertSeq`. I understand the extension was renamed to "Insert Seq" instead of "Insert Nums", but there's no difference between the two commands right? It's confusing to have both of them. I would hide the old `insertNums` command by including a `when` clause of [a custom clause context](https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context); let's call the clause `hideOldInsertCommand`. Then when someone uses `insertSeq`, the custom clause would change to true therefore hiding the old command. And when someone uses `insertNums`, we could add an action to the `showInformationMessage` that automatically changes the keybinds over and sets `hideOldInsertCommand = true`.
- [ ] I think there is a way to combine `insertSeq.showHistory` and `insertSeq`. I'm having trouble remembering where I saw this, but you can have up and down arrows scroll through history when using a text input, like with the default `insertSeq` command, then you don't *need* two commands to support history. I'll try to find that example somewhere.

**Comment by volkerdobler** [comment]
Hi  Noah,

> * [ ]  Rename the text description of `insertSeq` to `Insert Number Sequence`. I didn't even know you registered the command to the command palette until I looked through the code because the extension is called `Insert Seq` while the command is `Insert Numbers`. I was searching "seq" and didn't find anything.

I will delete the insertnum command with the next version. The name "insertnums" was the original name by James Brooks, who wrote the original extension for sublime. I used his python script and rewrite it to javascript. Therefore, I had an emotional bondage to "insertnums", but during the time I feel it limits the idea of the extension. So I changed it to insertseq, but did not find a way to change the way of the extension in the marketplace. The only way would be to delete the old extension and upload a new one. Also the name of this github is insertnums :-) 
But history should be not limiting our future, so I will delete the old command. I think, at the time when the command was insertnums, only a few dozend users used the extension.

> * [ ]  I would switch the prompt and the placeholder so you always see the text `[<start>][:<step>] ...` and don't have to memorize the formatting special characters.

I switched the prompt already, did you see it. But currently, I have the feeling, it's too long now.

> * [ ]  I don't know the history of the commands `insertNums` vs `insertSeq`. I understand the extension was renamed to "Insert Seq" instead of "Insert Nums", but there's no difference between the two commands right? It's confusing to have both of them. I would hide the old `insertNums` command by including a `when` clause of [a custom clause context](https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context); let's call the clause `hideOldInsertCommand`. Then when someone uses `insertSeq`, the custom clause would change to true therefore hiding the old command. And when someone uses `insertNums`, we could add an action to the `showInformationMessage` that automatically changes the keybinds over and sets `hideOldInsertCommand = true`.

See above, I think I can "delete" the old command and just use insertseq.

> * [ ]  I think there is a way to combine `insertSeq.showHistory` and `insertSeq`. I'm having trouble remembering where I saw this, but you can have up and down arrows scroll through history when using a text input, like with the default `insertSeq` command, then you don't _need_ two commands to support history. I'll try to find that example somewhere.

Again, this was because of history reason. In the first version I wrote, I wanted to have a history but did not know much about vscode, typescript and all the stuff. So I wrote a kind of "bash" history, because it seems easy to implement "!" as history char. Later, one of the users suggested to write a "proper" history, but you are right, could be only one, if the "up and down" arrow would work. Most of the time, it is even faster to type 1:1 than arrow up ;-)

**Comment by nmay231** [comment]
> See above, I think I can "delete" the old command and just use insertseq.

Gotcha. That's much simpler haha.

> Rename the text description of `insertSeq` to "Insert Number Sequence".

I'm talking about the command itself, not the package name. Like what you would search after opening the command palette with `ctrl+shift+P`. I originally thought I *had* to use `ctrl+alt+.` to use this extension because I didn't know the command description is "Insert Numbers". Either "Insert Number Sequence" or "Insert Numbers or Sequence" is good because it allows you to search "sequence" in the command palette. 

> I switched the prompt already, did you see it. But currently, I have the feeling, it's too long now.

I mean you should swap `prompt` and `placeholder` in the call to `.showInputBox()` to get something like:

![image](https://github.com/volkerdobler/insertnums/assets/35386821/987f821b-9035-459c-ac65-89cb2d6a3a45)

Then you can always see the format while typing in the input. Though, yes, it is a bit long...

> Also the name of this github is insertnums :-)

You don't have to change it, but if you want to have everything to be consistent, you can rename the repo and all the old URLs will redirect correctly.

> Most of the time, it is even faster to type 1:1 than arrow up ;-)

Very true haha. Reminds me of this meme https://www.reddit.com/r/linuxmasterrace/comments/pbyeaa/command_line_history/

**Comment by volkerdobler** [comment]
> > Rename the text description of `insertSeq` to "Insert Number Sequence".

New name will be "Insert Sequence" ;-)

> I mean you should swap `prompt` and `placeholder` in the call to `.showInputBox()` to get something like:
> 
> ![image](https://private-user-images.githubusercontent.com/35386821/324133994-987f821b-9035-459c-ac65-89cb2d6a3a45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MzA5NTEsIm5iZiI6MTcxMzczMDY1MSwicGF0aCI6Ii8zNTM4NjgyMS8zMjQxMzM5OTQtOTg3ZjgyMWItOTAzNS00NTljLWFjNjUtODljYjJkNmEzYTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDIwMTczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMzNjYjA2MDYzOTZiMDM5ZmMwZDhjNGQzZTRhMTc2NGM3YWY3ZDgzZTEzYWY2OTA3ZWYxMTg3NzUxYjYxZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ae0pHG0LzuInOLC4jEQblsS1ivJhGsQluv1MjLP8K_Y)
> 
> Then you can always see the format while typing in the input. Though, yes, it is a bit long...

Ah, now I understand. Good idea, will be changed in next version.

**Comment by volkerdobler** [comment]
> > > Rename the text description of `insertSeq` to "Insert Number Sequence".
> 
> New name will be "Insert Sequence" ;-)
> 
> > I mean you should swap `prompt` and `placeholder` in the call to `.showInputBox()` to get something like:
> > ![image](https://private-user-images.githubusercontent.com/35386821/324133994-987f821b-9035-459c-ac65-89cb2d6a3a45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MzA5NTEsIm5iZiI6MTcxMzczMDY1MSwicGF0aCI6Ii8zNTM4NjgyMS8zMjQxMzM5OTQtOTg3ZjgyMWItOTAzNS00NTljLWFjNjUtODljYjJkNmEzYTQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDIwMTczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMzNjYjA2MDYzOTZiMDM5ZmMwZDhjNGQzZTRhMTc2NGM3YWY3ZDgzZTEzYWY2OTA3ZWYxMTg3NzUxYjYxZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ae0pHG0LzuInOLC4jEQblsS1ivJhGsQluv1MjLP8K_Y)
> > Then you can always see the format while typing in the input. Though, yes, it is a bit long...
> 
> Ah, now I understand. Good idea, will be changed in next version.

Is changed in version 0.9.6
