### ISSUE TITLE
Negative number error

### ISSUE THREAD

**Issue by douniwan5788** [volkerdobler/insertnums#20]
```
[insertseq] No valid regular expression: >-2<. DEFAULT: 1:1 Options: NUMBERS:  [<start>][:<step>][~<format>][r+?<to>]][*<frequency>][#repetitions][::<expr>][@<stopexpr>][$][!] or ALPHA:  <a-z+|A-Z+> [:<step>][~<format>][*<frequency>][#repetitions][@<stopexpr>][w][$][!] or <year>[-<month>[-<day>]] [:<datestep>] [~<dateformat>] [*<frequency>][#repetitions][$][!]SUBSTITUTION: [<cast>]|[~<format>::]<expr>[@<stopexpr>][$][!] or MONTH:  ;<monthname>|<monthnumber> [:<step>][~<format>][*<frequency>][#repetitions][@<stopexpr>][[<lang>]][$][!] or (deprecated) HISTORY: !(!|pd+|c|d+ with !! = prev. command, !c = clear history 
```

**Comment by douniwan5788** [comment]
https://github.com/volkerdobler/insertnums/blob/14732c27614150fc97991b6c45f2772f5df5d396/src/extension.ts#L326

The `lead_char` must match at least 1 character when '+' or '-' exists.

**Comment by volkerdobler** [comment]
Thank for letting me know about this bug. Will be fixed in the next few days.

**Comment by volkerdobler** [comment]
@douniwan5788 I just published version 0.10.1 and I hope I fixed the problem ;-) Please let me know, if it works for you

**Comment by douniwan5788** [comment]
Yeah, a single negative number is fixed, but it still behaves strangely with lead_char. like `-     5@i>10`

**Comment by volkerdobler** [comment]
Hi @douniwan5788, for me it looks fine with "- 5@i>10".

![image](https://github.com/user-attachments/assets/45f224bc-62da-4fea-8338-32e964707731)

Regards,
Volker

**Comment by volkerdobler** [comment]
Hi @douniwan5788,

I am not sure, what you expected. You have the choice:

"- 5@i>10" will bring the leading chars between the minus sign and the number:

```
- 5
- 4
- 3
- 2
- 1
 0
 1
 2
 3
 4
 5
```

If you want to have the leading char BEFORE the negativ sign char, you have to write it as " -5@i>10" (leading chars will be recognized also before the "-" sign as leading char - so "000-5" is -5 with three leading zeros).

```
 −5
 −4
 −3
 −2
 −1
  0
  1
  2
  3
  4
  5
```

I have think about this second behaviour of putting two leading chars infront of positiv numbers, even that you mentioned only one leading char. I think it is a bug and this will be fixed today with version 0.10.2.

Do you have any additional concerns or issues?

Best regards,
Volker

**Comment by douniwan5788** [comment]
Yeah, it's fixed. I got it wrong. Great work!

**Comment by volkerdobler** [comment]
Thanks @douniwan5788 for your feedback. I just played arround and I will not release version 0.10.2 as I think, the current behaviour is best regarding the "positiv" sequence. If I want to have leading chars (e.g. blanks) infront of negative numbers, it should bring negative signs included in the number printed.

Glad I could help, if you need any further help, please let me know and I will reopen this issue.

Regards,
Volker
