### ISSUE TITLE
random integer?

### ISSUE THREAD

**Issue by Ron2014** [volkerdobler/insertnums#3]
What I usually use is generate random integer and insert into my case file, because I'm doing the algorithm coding homework.

In the homework, many problem are about array statistic, need using dynamic planning to solve.  And the input array is often very long, like 100000 and above. Judge online system give me 'Out of Time' result, and show nothing about the case. So I need generate the 100000 integer by myself.

I use this like 

```
::Math.ceil(Math.random()*100000)@i>100000
```

but for me it's very uncomfortable to input so long javascript expression very time.  And the command line have no memory too. CTL + ALT + DOT  get the command window and type this FROM BLANK, and again and again...ummm....

Can you impove this situation?

PS. I've searched every `Random Num` `Insert Num` VS code extension projects. Only this one can REALLY insert lines without making multiline selection first, even it can use javascript to do more jobs like random.  It's awesome!

**Comment by volkerdobler** [comment]
Hi @Ron2014,

thanks for your comment. Glad you can (mainly) use the extension.

Your expression works on my computer - but I use a fast PC with a lot of RAM.
The current timeout is 1 second and everything which needs longer than 1 seconds gets a time out - I can increase this limit easily to 10 or 30 seconds. Which might be a problem if someone is wondering, what happens and can not see that something is still working ...

The other (good) point is a kind of "history" in the input line. I haven't think about this yet and I am not sure if I can implement this within standard VSCode Input Boxes. I will have a look about this and let you know what's possible.

Again, thanks for your feedback and I will have a look at them.

Volker

**Comment by Ron2014** [comment]
Emmm... judge online system is a web application [like this](https://leetcode.com/explore/) where I can take challeges of algorithm problems and coding to solve them, the web provide a compiler to check if my code really solve the problem. So don't mind the 'input very long' 'Out of Time' 'don't show the case'  and anything else I said at the second line above, that's only a statement to explain why I need random function, I use random function to do what. 

That 'Out of Time' is not about your extension, it's about my code in the judge online.

Hope 'the history in input window' can be implement, using the UP/DOWN arrow to switch last or newer command typed.  If it's impossible,  for the `random function`, maybe you can add an extra `text pattern command` like

```
?1,100000@i>100000
```
or 
```
?100000@i>100000
```
`?` (or other character if you like) tells it's the beginning of random function, and random from [1, 100000], minimum 1 is default. 

Ron

**Comment by volkerdobler** [comment]
Hi Ron,
I just updated the extension to version 0.4.0
It includes two new features (you requested ;-) ).
1. You can now easily insert random numbers (see "r"-Option for numbers)
2. You can use a bash-like history (used with !).

Unfortunately, vscode currently does not allow to have a history (see issue here: https://github.com/microsoft/vscode/issues/97655) - it might be coming but currently, the support is very low. So I decided to implement a command-line history.

All new features are described in details in the README file. Hope it helps.

**Comment by Ron2014** [comment]
Thanks Volker, it helps me too much!

Ron.
